#baseURL = "https://tatianavelasco.netlify.app/"
title = "Tatiana Velasco Rodriguez"
baseURL = "https://tativelasco.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Tatiana Velasco"
  description = "Ph.D. Student - Columbia University"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  profilePicture = "images/me.jpg"
  [params.footer]
    text = "By Hugo Reseacher"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

# [[params.socialIcons]]
# icon = "fa-envelope"
# title = "e-mail"
# url = "mailto:tv2225@tc.columbia.edu"

# [[params.socialIcons]]
#     name = "Twitter"
#     icon = "fa-twitter"
#     url = "https://twitter.com/TatiVelasco/"
#     [[params.socialIcons]]
#     icon = "fa-github"
#     title = "GitHub"
#     url = "https://github.com/tativelasco/"

 # [[params.socialIcons]]
# icon = "fa-linkedin"
# title = "Linkedin"
# url = "https://www.linkedin.com/in/tatianavelascoro/"



## Menu items

#[menu]

#  [[menu.main]]
#  name = "Home"
#  identifier = "home"
#  weight = 100
#  url = "/"

  #[[menu.main]]
  #name = "Research"
  #weight = 200
  #identifier = "research"
  #url = "research/"

  #[[menu.main]]
  #name = "CV"
  #weight = 300
  #identifier = "cv"
  #url = "cv/"

#  [[menu.main]]
#  name = "About"
#  weight = 400
#  identifier = "about"
#  url = "about/"

  #############################
  #############################
